//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registered_courses
    {
        public int id { get; set; }
        public string TrainingName { get; set; }
        public Nullable<int> Course_id { get; set; }
        public string FirstName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Fees { get; set; }
        public string Status { get; set; }
    
        public virtual Course_Registration Course_Registration { get; set; }
    }
}
